### ISSUE TITLE
Query sampling rate

### ISSUE THREAD

**Issue by mchitre** [baggepinnen/LazyWAVFiles.jl#8]
It would be nice to return the sampling rate of the file when the file is first opened. With `wavread`, you'd normally do `data, fs = wavread(...)`. Something similar: `data, fs = LazyWAVFile(...)` perhaps?

**Comment by baggepinnen** [comment]
Good idea! The samplerate is now stored in the field `fs` in both lazy files and distributed files. It's now illegal to create distributed files where the underlying files have varying sample rate.
